# Generated by Django 2.1.3 on 2018-11-26 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtrack', '0002_auto_20181117_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriodConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_schedule', models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100)),
                ('start_from', models.DateField()),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100)),
                ('org_description', models.TextField(max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_board', models.BooleanField()),
                ('verified_list', models.BooleanField()),
                ('post_title', models.CharField(blank=True, default='A Snappy Post Title', max_length=140)),
                ('about_me', models.TextField(blank=True, default="I don't want to brag, but I'm the best!", max_length=280)),
                ('how i can help', models.TextField(blank=True, default="Here's what I'm going to do for you", max_length=280)),
            ],
        ),
        migrations.RemoveField(
            model_name='payperiodconf',
            name='employer',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='employmentdetail',
            old_name='employee',
            new_name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='about_me',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='employed',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='how i can help',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='job_board',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='post_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='verified_list',
        ),
        migrations.RemoveField(
            model_name='payperiod',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='payperiod',
            name='employer',
        ),
        migrations.AddField(
            model_name='payperiod',
            name='candidate',
            field=models.ManyToManyField(help_text='Select candidates that worked during this period', to='cbtrack.Candidate'),
        ),
        migrations.AddField(
            model_name='payperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('j', 'Journeyperson'), ('a', 'Apprentice'), ('o', 'Non-trades')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='employmentdetail',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='PayPeriodConf',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtrack.Candidate'),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
