# Generated by Django 2.1.3 on 2018-11-26 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbtrack', '0003_auto_20181126_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbtrack.Candidate')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('employment_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbtrack.EmploymentDetail')),
            ],
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='employer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cbtrack.Profile'),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('twice_per_month', 'Twice per month'), ('monthly', 'Monthly')], default='every_two_weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='about_me',
            field=models.TextField(blank=True, default="I don't want to brag, but I'm the best!", max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='how i can help',
            field=models.TextField(blank=True, default="Here's what I'm going to do for you", max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='servicedetail',
            name='post_title',
            field=models.CharField(blank=True, default='A Snappy Post Title', max_length=140, null=True),
        ),
    ]
