# Generated by Django 2.1.3 on 2018-11-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0004_auto_20181126_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('j', 'Journeyperson'), ('o', 'Non-trades'), ('a', 'Apprentice')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('twice_per_month', 'Twice per month'), ('monthly', 'Monthly'), ('every_two_weeks', 'Every two weeks')], default='every_two_weeks', max_length=100),
        ),
    ]
