# Generated by Django 2.1.3 on 2018-11-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0005_auto_20181126_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('sp', 'Service Provider'), ('emp', 'Employer')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date registered in the tracker'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('a', 'Apprentice'), ('j', 'Journeyperson')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiod',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('twice_per_month', 'Twice per month'), ('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='every_two_weeks', max_length=100),
        ),
    ]
