# Generated by Django 2.1.3 on 2018-11-28 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0006_auto_20181128_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('j', 'Journeyperson'), ('a', 'Apprentice'), ('o', 'Non-trades')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('emp', 'Employer'), ('sp', 'Service Provider')], max_length=100, null=True),
        ),
    ]
