# Generated by Django 2.1.3 on 2018-11-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0008_auto_20181128_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicedetail',
            name='how i can help',
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='how_help',
            field=models.TextField(blank=True, default="Here's what I'm going to do for you", max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('a', 'Apprentice'), ('o', 'Non-trades'), ('j', 'Journeyperson')], default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('every_two_weeks', 'Every two weeks'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('emp', 'Employer'), ('sp', 'Service Provider')], max_length=100, null=True),
        ),
    ]
