# Generated by Django 2.1.3 on 2018-11-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0009_auto_20181128_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(help_text='Email', max_length=254),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_name',
            field=models.CharField(help_text='First name', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='last_name',
            field=models.CharField(help_text='Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('a', 'Apprentice'), ('o', 'Non-trades'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('sp', 'Service Provider'), ('emp', 'Employer')], max_length=100, null=True),
        ),
    ]
