# Generated by Django 2.1.3 on 2018-11-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0010_auto_20181128_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('fa_icon', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('a', 'Apprentice'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('every_two_weeks', 'Every two weeks'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('emp', 'Employer'), ('sp', 'Service Provider')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicedetail',
            name='top_trades',
            field=models.ManyToManyField(blank=True, null=True, to='cbtrack.TopTrades'),
        ),
    ]
