# Generated by Django 2.1.3 on 2018-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('cbtrack', '0011_auto_20181128_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopTrades',
            new_name='TopTrade',
        ),
        migrations.RenameField(
            model_name='servicedetail',
            old_name='top_trades',
            new_name='top_trade',
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('twice_per_month', 'Twice per month'), ('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='every_two_weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('sp', 'Service Provider'), ('emp', 'Employer')], max_length=100, null=True),
        ),
    ]
