# Generated by Django 2.1.3 on 2018-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0012_auto_20181128_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('a', 'Apprentice'), ('o', 'Non-trades'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('twice_per_month', 'Twice per month'), ('every_two_weeks', 'Every two weeks')], default='every_two_weeks', max_length=100),
        ),
    ]
