# Generated by Django 2.1.3 on 2018-11-28 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0013_auto_20181128_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('twice_per_month', 'Twice per month'), ('monthly', 'Monthly')], default='every_two_weeks', max_length=100),
        ),
    ]
