# Generated by Django 2.1.3 on 2018-11-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0016_auto_20181128_1512'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedetail',
            options={'permissions': (('service_detail_admin', 'Create, Update, and Delete service details'),)},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('j', 'Journeyperson'), ('a', 'Apprentice')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('twice_per_month', 'Twice per month'), ('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly')], default='every_two_weeks', max_length=100),
        ),
    ]
