# Generated by Django 2.1.3 on 2018-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0017_auto_20181130_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('a', 'Apprentice'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
    ]
