# Generated by Django 2.1.3 on 2018-11-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0018_auto_20181130_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmentdetail',
            options={'permissions': (('employment_detail_admin', 'Create, Update, and Delete employment details'),)},
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('j', 'Journeyperson'), ('o', 'Non-trades'), ('a', 'Apprentice')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
    ]
