# Generated by Django 2.1.3 on 2018-12-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0020_auto_20181204_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payperiod',
            name='candidate',
        ),
        migrations.AddField(
            model_name='payperiod',
            name='employment_detail',
            field=models.ManyToManyField(help_text='Select candidates that worked during this period', to='cbtrack.EmploymentDetail'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('a', 'Apprentice'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
    ]
