# Generated by Django 2.1.3 on 2018-12-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0021_auto_20181204_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payperiod',
            name='total trade hours worked',
        ),
        migrations.AddField(
            model_name='payperiod',
            name='trade_hours',
            field=models.IntegerField(blank=True, help_text='total trade hours worked', null=True),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('twice_per_month', 'Twice per month'), ('every_two_weeks', 'Every two weeks')], default='every_two_weeks', max_length=100),
        ),
    ]
