# Generated by Django 2.1.3 on 2018-12-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0024_auto_20181205_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('every_two_weeks', 'Every two weeks'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
    ]
