# Generated by Django 2.1.3 on 2018-12-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbtrack', '0029_auto_20181205_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='trade_status',
            field=models.CharField(choices=[('o', 'Non-trades'), ('a', 'Apprentice'), ('j', 'Journeyperson')], default='a', help_text='Trade status', max_length=100),
        ),
        migrations.AlterField(
            model_name='payperiodconfig',
            name='pay_schedule',
            field=models.CharField(choices=[('every_two_weeks', 'Every two weeks'), ('monthly', 'Monthly'), ('twice_per_month', 'Twice per month')], default='every_two_weeks', max_length=100),
        ),
    ]
